project:
  type: website
  output-dir: docs

website:
  title: "Walking SALURBAL-Climate Proposal"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: true
    smooth-scroll: true
    anchor-sections: true
    page-layout: full

execute:
  freeze: auto
  cache: true
  warning: false
  message: false